### ISSUE TITLE
Unexpected Status when sending Event

### ISSUE THREAD

**Issue by bobhenl** [tebexio/Tebex-Minecraft#79]
- Server type: Purpur 1.21.4
- Tebex plugin: 2.2.0
- Description of the issue:
I'm getting the error below

```yml
java.io.IOException: Unexpected status code (400)[19:21:28 ERROR]: [Tebex] Unexpected status code when sending server events

        at tebex-bukkit-2.2.0.jar//io.tebex.sdk.SDK.lambda$_batchServerEvents$17(SDK.java:610)
        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179)
        at tebex-bukkit-2.2.0.jar//io.tebex.sdk.request.TebexRequest$1.onResponse(TebexRequest.java:145)
        at tebex-bukkit-2.2.0.jar//io.tebex.plugin.libs.okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by hardcorefactions** [comment]
same on 1.8.8

```
[04:09:42 ERROR]: [Tebex] Unexpected status code when sending server events
[04:09:42 WARN]: java.io.IOException: Unexpected status code (400)
[04:09:42 WARN]:        at io.tebex.sdk.SDK.lambda$_batchServerEvents$17(SDK.java:610)
[04:09:42 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
[04:09:42 WARN]:        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
[04:09:42 WARN]:        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179)
[04:09:42 WARN]:        at io.tebex.sdk.request.TebexRequest$1.onResponse(TebexRequest.java:145)
[04:09:42 WARN]:        at io.tebex.plugin.libs.okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
[04:09:42 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[04:09:42 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[04:09:42 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by WildBamaBoy** [comment]
Hi, please enable debug mode using `tebex.debug true`. This will show both the request and response in your server log. Please then attach the relevant logs from the Tebex plugin.

**Comment by bobhenl** [comment]
```yml
6:50:48] [Craft Scheduler Thread - 69 - Tebex/INFO]: [Tebex] [DEBUG] Checking for due players...
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG]  -> POST https://plugin.tebex.io/events | [
  {
    "username_id": "a4e11efc-7feb-4e2a-acb5-4b642438f6a7",
    "username": "Renzotom",
    "ip": "XXX",
    "event_type": "server.join",
    "event_date": "2025-03-10T16:50:34.984599346Z"
  }
]
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG]  -> GET https://plugin.tebex.io/queue | No body
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] 400 <- POST https://plugin.tebex.io/events 
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG]  | {"error_code":400,"error_message":"Please provide a valid date for all events."}
[16:50:48] [OkHttp https://plugin.tebex.io/.../ERROR]: [Tebex] Unexpected status code when sending server events
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Successfully sent join events.
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] 200 <- GET https://plugin.tebex.io/queue 
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG]  | {"meta":{"execute_offline":false,"next_check":60,"more":false},"players":[{"id":13833738,"name":"_dasniper125","uuid":null},{"id":14423122,"name":"baglisting","uuid":null},{"id":8761603,"name":"Waggzzzzz","uuid":null},{"id":10542750,"name":"legendxadz","uuid":null},{"id":10026405,"name":"Ghost_Hunter918","uuid":null},{"id":13209916,"name":"pianomanYT","uuid":null},{"id":14578773,"name":"IamSteevee","uuid":null},{"id":14579158,"name":"BwBoiBrother","uuid":null},{"id":13022067,"name":"Demasopr","uuid":null},{"id":13912030,"name":"DAHtaz2345","uuid":null},{"id":14595955,"name":"Loisl76","uuid":null},{"id":8712439,"name":"MarianoAF","uuid":null},{"id":14318140,"name":"Firelanden251","uuid":null},{"id":9273158,"name":"alegre211piloto","uuid":null},{"id":12834987,"name":"ItzGooMC_","uuid":null},{"id":12886803,"name":"YT_JBCraft","uuid":null},{"id":12997020,"name":"ItsWheezy_","uuid":null},{"id":12201793,"name":".Mckenziepup4865","uuid":null},{"id":12231798,"name":"_McKenziepup4865","uuid":null},{"id":13011565,"name":"Duckyking29","uuid":null},{"id":14556222,"name":"brandyagbada","uuid":null},{"id":14216676,"name":"Noobisbest2233","uuid":null},{"id":13212443,"name":"Mapyr","uuid":null},{"id":14632054,"name":"Hannavok14","uuid":null},{"id":14632241,"name":"k1oushs","uuid":null},{"id":12957363,"name":"purav1","uuid":null},{"id":14640629,"name":"WolfWolf88","uuid":null},{"id":14343234,"name":"M1keyGTR","uuid":null},{"id":14648818,"name":"tgcriminal00112","uuid":null},{"id":14285101,"name":"Jacenthangggg","uuid":null},{"id":14653400,"name":"king__abbas","uuid":null},{"id":13466787,"name":"FarsicsXD","uuid":null},{"id":14659553,"name":"BmwPhoenix","uuid":null},{"id":14660868,"name":"_SkaterBoyHan","uuid":null},{"id":13944125,"name":"ApplePie1031","uuid":null},{"id":14664525,"name":"siggepigge12124","uuid":null},{"id":14667415,"name":"WhySiphon","uuid":null},{"id":2505306,"name":"LOVEBLUE","uuid":null},{"id":13904335,"name":"Ketchupguy2344","uuid":null},{"id":14430277,"name":"Dasniper125","uuid":null},{"id":14702208,"name":"ochekz","uuid":null},{"id":14702426,"name":"WaterPhish","uuid":null},{"id":14541076,"name":"_Mick3yMouse16","uuid":null},{"id":10218669,"name":"mkuusk","uuid":null},{"id":12722184,"name":"legoNinja7594","uuid":null},{"id":14693687,"name":"Anime_Character","uuid":null},{"id":13517491,"name":"danihack","uuid":null},{"id":2241100,"name":"kiki","uuid":null},{"id":14726495,"name":"hawktuahlord69ah","uuid":null},{"id":12328863,"name":"Aaravos2312","uuid":null}]}
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Found 50 players with pending commands.
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Processing online commands for player '_dasniper125'...
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Player _dasniper125 has online commands but is not connected. Skipping.
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Processing online commands for player 'baglisting'...
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Player baglisting has online commands but is not connected. Skipping.
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Processing online commands for player 'Waggzzzzz'...
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Player Waggzzzzz has online commands but is not connected. Skipping.
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Processing online commands for player 'legendxadz'...
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Player legendxadz has online commands but is not connected. Skipping.
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Processing online commands for player 'Ghost_Hunter918'...
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Player Ghost_Hunter918 has online commands but is not connected. Skipping.
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Processing online commands for player 'pianomanYT'...
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Player pianomanYT has online commands but is not connected. Skipping.
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Processing online commands for player 'IamSteevee'...
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Player IamSteevee has online commands but is not connected. Skipping.
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Processing online commands for player 'BwBoiBrother'...
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Player BwBoiBrother has online commands but is not connected. Skipping.
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Processing online commands for player 'Demasopr'...
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Player Demasopr has online commands but is not connected. Skipping.
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Processing online commands for player 'DAHtaz2345'...
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Player DAHtaz2345 has online commands but is not connected. Skipping.
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Processing online commands for player 'Loisl76'...
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Player Loisl76 has online commands but is not connected. Skipping.
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Processing online commands for player 'MarianoAF'...
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Player MarianoAF has online commands but is not connected. Skipping.
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Processing online commands for player 'Firelanden251'...
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Player Firelanden251 has online commands but is not connected. Skipping.
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Processing online commands for player 'alegre211piloto'...
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Player alegre211piloto has online commands but is not connected. Skipping.
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Processing online commands for player 'ItzGooMC_'...
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Player ItzGooMC_ has online commands but is not connected. Skipping.
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Processing online commands for player 'YT_JBCraft'...
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Player YT_JBCraft has online commands but is not connected. Skipping.
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Processing online commands for player 'ItsWheezy_'...
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Player ItsWheezy_ has online commands but is not connected. Skipping.
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Processing online commands for player '.Mckenziepup4865'...
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Player .Mckenziepup4865 has online commands but is not connected. Skipping.
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Processing online commands for player '_McKenziepup4865'...
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Player _McKenziepup4865 has online commands but is not connected. Skipping.
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Processing online commands for player 'Duckyking29'...
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Player Duckyking29 has online commands but is not connected. Skipping.
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Processing online commands for player 'brandyagbada'...
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Player brandyagbada has online commands but is not connected. Skipping.
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Processing online commands for player 'Noobisbest2233'...
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Player Noobisbest2233 has online commands but is not connected. Skipping.
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Processing online commands for player 'Mapyr'...
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Player Mapyr has online commands but is not connected. Skipping.
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Processing online commands for player 'Hannavok14'...
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Player Hannavok14 has online commands but is not connected. Skipping.
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Processing online commands for player 'k1oushs'...
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Player k1oushs has online commands but is not connected. Skipping.
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Processing online commands for player 'purav1'...
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Player purav1 has online commands but is not connected. Skipping.
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Processing online commands for player 'WolfWolf88'...
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Player WolfWolf88 has online commands but is not connected. Skipping.
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Processing online commands for player 'M1keyGTR'...
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Player M1keyGTR has online commands but is not connected. Skipping.
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Processing online commands for player 'tgcriminal00112'...
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Player tgcriminal00112 has online commands but is not connected. Skipping.
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Processing online commands for player 'Jacenthangggg'...
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Player Jacenthangggg has online commands but is not connected. Skipping.
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Processing online commands for player 'king__abbas'...
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Player king__abbas has online commands but is not connected. Skipping.
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Processing online commands for player 'FarsicsXD'...
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Player FarsicsXD has online commands but is not connected. Skipping.
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Processing online commands for player 'BmwPhoenix'...
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Player BmwPhoenix has online commands but is not connected. Skipping.
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Processing online commands for player '_SkaterBoyHan'...
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Player _SkaterBoyHan has online commands but is not connected. Skipping.
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Processing online commands for player 'ApplePie1031'...
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Player ApplePie1031 has online commands but is not connected. Skipping.
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Processing online commands for player 'siggepigge12124'...
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Player siggepigge12124 has online commands but is not connected. Skipping.
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Processing online commands for player 'WhySiphon'...
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Player WhySiphon has online commands but is not connected. Skipping.
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Processing online commands for player 'LOVEBLUE'...
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Player LOVEBLUE has online commands but is not connected. Skipping.
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Processing online commands for player 'Ketchupguy2344'...
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Player Ketchupguy2344 has online commands but is not connected. Skipping.
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Processing online commands for player 'Dasniper125'...
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Player Dasniper125 has online commands but is not connected. Skipping.
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Processing online commands for player 'ochekz'...
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Player ochekz has online commands but is not connected. Skipping.
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Processing online commands for player 'WaterPhish'...
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Player WaterPhish has online commands but is not connected. Skipping.
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Processing online commands for player '_Mick3yMouse16'...
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Player _Mick3yMouse16 has online commands but is not connected. Skipping.
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Processing online commands for player 'mkuusk'...
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Player mkuusk has online commands but is not connected. Skipping.
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Processing online commands for player 'legoNinja7594'...
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Player legoNinja7594 has online commands but is not connected. Skipping.
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Processing online commands for player 'Anime_Character'...
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Player Anime_Character has online commands but is not connected. Skipping.
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Processing online commands for player 'danihack'...
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Player danihack has online commands but is not connected. Skipping.
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Processing online commands for player 'kiki'...
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Player kiki has online commands but is not connected. Skipping.
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Processing online commands for player 'hawktuahlord69ah'...
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Player hawktuahlord69ah has online commands but is not connected. Skipping.
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Processing online commands for player 'Aaravos2312'...
[16:50:48] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] [DEBUG] Player Aaravos2312 has online commands but is not connected. Skipping.

**Comment by ChrisTVH** [comment]
It also happens to me since I upgraded to tebex 2.2.0 when joining one or more of them.
https://mclo.gs/hcUJnjo

**Comment by ArikSquad** [comment]
+1, same error

**Comment by andrewkm** [comment]
We are running Paper 1.21.4 and getting spammed with this constantly.
Using Tebex 2.2.0 - bf3242b
Please provide a hotfix @WildBamaBoy 

```java[21:19:22] [OkHttp https://plugin.tebex.io/.../ERROR]: [Tebex] Unexpected status code when sending server events
[21:19:22] [OkHttp https://plugin.tebex.io/.../WARN]: java.io.IOException: Unexpected status code (400)
[21:19:22] [OkHttp https://plugin.tebex.io/.../WARN]: 	at tebex-bukkit-2.2.0.jar//io.tebex.sdk.SDK.lambda$_batchServerEvents$17(SDK.java:610)
[21:19:22] [OkHttp https://plugin.tebex.io/.../WARN]: 	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1194)
[21:19:22] [OkHttp https://plugin.tebex.io/.../WARN]: 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:554)
[21:19:22] [OkHttp https://plugin.tebex.io/.../WARN]: 	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2223)
[21:19:22] [OkHttp https://plugin.tebex.io/.../WARN]: 	at tebex-bukkit-2.2.0.jar//io.tebex.sdk.request.TebexRequest$1.onResponse(TebexRequest.java:145)
[21:19:22] [OkHttp https://plugin.tebex.io/.../WARN]: 	at tebex-bukkit-2.2.0.jar//io.tebex.plugin.libs.okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
[21:19:22] [OkHttp https://plugin.tebex.io/.../WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[21:19:22] [OkHttp https://plugin.tebex.io/.../WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:19:22] [OkHttp https://plugin.tebex.io/.../WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1575)
```

**Comment by ZekeZDev** [comment]
just to quickly ask here since this seems similar to the error I am having on fabric does the link sent to chat send you all to the correct product page? see: #82

**Comment by crumpkatrina** [comment]
Same issue here, the new version is absolutely filled to the brim with these errors. Downgraded to 2.1.0 due to the spam.

**Comment by WildBamaBoy** [comment]
Fixed in 20d10b9

**Comment by Goinging** [comment]
I don't think this fixed it. I compiled a jar myself from the newest github commit

**Comment by WildBamaBoy** [comment]
> I don't think this fixed it. I compiled a jar myself from the newest github commit

If the issue still occurs for your store, please share relevant logs and traces.

**Comment by ZekeZDev** [comment]
> Fixed in [20d10b9](https://github.com/tebexio/Tebex-Minecraft/commit/20d10b91e1997ae89da3a5d96a59f5942cd10305)

No longer getting this error personally however the link is still incorrect for the product page I have now made that a seperate issue #85

**Comment by andrewkm** [comment]
Looks to be fixed on my end.
Running on:
Paper 1.21.4 Build 212
Tebex Build https://github.com/tebexio/Tebex-Minecraft/commit/3e2c00702b0e654a5b1433e50ad39367aa91688e
